import type { TestCatalogItem, CollectionCenter } from "./types";

export const DEFAULT_COLLECTION_CENTERS: CollectionCenter[] = [
  {
    id: "center-01",
    code: "CC-CENTRAL",
    name: "Arogya Main Hospital Lab & Diagnostic Core",
    address: "Block A, Medical Enclave, Health City",
    city: "Hyderabad",
    contactNumber: "+91 40 2345 6789",
    inCharge: "Dr. R. K. Varma (Chief Pathologist)",
    activeSamplesCount: 42,
  },
  {
    id: "center-02",
    code: "CC-BANJARA",
    name: "Banjara Hills Outreach Phlebotomy Center",
    address: "Road No. 12, Banjara Hills",
    city: "Hyderabad",
    contactNumber: "+91 40 8899 0011",
    inCharge: "S. Priya (Phlebotomy Lead)",
    activeSamplesCount: 18,
  },
  {
    id: "center-03",
    code: "CC-MADHAPUR",
    name: "HITEC City IT Corridor Collection Hub",
    address: "Cyber Towers Junction, Madhapur",
    city: "Hyderabad",
    contactNumber: "+91 40 7766 5544",
    inCharge: "K. Mohan (Collection Officer)",
    activeSamplesCount: 27,
  },
  {
    id: "center-04",
    code: "CC-SECUNDERABAD",
    name: "Secunderabad Metro Diagnostics Point",
    address: "Station Road, Secunderabad",
    city: "Secunderabad",
    contactNumber: "+91 40 3322 1100",
    inCharge: "M. Anuradha (Center Manager)",
    activeSamplesCount: 15,
  },
];

export const DIAGNOSTIC_TEST_CATALOG: TestCatalogItem[] = [
  {
    id: "test-cbc",
    code: "HEM-001",
    name: "Complete Blood Count (CBC) with Automated Differential",
    department: "Hematology",
    tubeType: "Lavender (EDTA)",
    specimen: "Whole Blood EDTA (3 mL)",
    fastingRequired: false,
    tatMinutes: 60,
    price: 350,
    clinicalSignificance: "Primary screening for anemia, infection, leukemias, and thrombocytopenia.",
    parameters: [
      { id: "p-hb", name: "Hemoglobin", unit: "g/dL", refLow: 13.0, refHigh: 17.0, criticalLow: 7.0, criticalHigh: 20.0, decimalPlaces: 1 },
      { id: "p-rbc", name: "RBC Count", unit: "mil/µL", refLow: 4.5, refHigh: 5.9, criticalLow: 2.5, criticalHigh: 6.8, decimalPlaces: 2 },
      { id: "p-wbc", name: "Total WBC Count", unit: "cells/µL", refLow: 4000, refHigh: 11000, criticalLow: 2000, criticalHigh: 30000, decimalPlaces: 0 },
      { id: "p-plt", name: "Platelet Count", unit: "lakh/µL", refLow: 1.5, refHigh: 4.5, criticalLow: 0.4, criticalHigh: 10.0, decimalPlaces: 2 },
      { id: "p-pcv", name: "Hematocrit (PCV)", unit: "%", refLow: 40.0, refHigh: 50.0, criticalLow: 20.0, criticalHigh: 60.0, decimalPlaces: 1 },
      { id: "p-mcv", name: "MCV", unit: "fL", refLow: 80.0, refHigh: 100.0, decimalPlaces: 1 },
      { id: "p-neut", name: "Neutrophils", unit: "%", refLow: 40.0, refHigh: 75.0, decimalPlaces: 1 },
      { id: "p-lymph", name: "Lymphocytes", unit: "%", refLow: 20.0, refHigh: 45.0, decimalPlaces: 1 },
    ],
  },
  {
    id: "test-lft",
    code: "BIO-002",
    name: "Liver Function Test (LFT) Comprehensive Panel",
    department: "Biochemistry",
    tubeType: "Gold / Red (SST / Serum)",
    specimen: "Clotted Blood Serum (4 mL)",
    fastingRequired: true,
    fastingHours: 8,
    tatMinutes: 90,
    price: 750,
    clinicalSignificance: "Evaluates hepatic synthetic function, cholestasis, and hepatocellular injury.",
    parameters: [
      { id: "p-tbil", name: "Bilirubin Total", unit: "mg/dL", refLow: 0.2, refHigh: 1.2, criticalHigh: 15.0, decimalPlaces: 2 },
      { id: "p-dbil", name: "Bilirubin Direct", unit: "mg/dL", refLow: 0.0, refHigh: 0.3, decimalPlaces: 2 },
      { id: "p-sgot", name: "AST / SGOT", unit: "U/L", refLow: 10.0, refHigh: 40.0, criticalHigh: 500.0, decimalPlaces: 1 },
      { id: "p-sgpt", name: "ALT / SGPT", unit: "U/L", refLow: 7.0, refHigh: 56.0, criticalHigh: 500.0, decimalPlaces: 1 },
      { id: "p-alp", name: "Alkaline Phosphatase (ALP)", unit: "U/L", refLow: 44.0, refHigh: 147.0, decimalPlaces: 0 },
      { id: "p-tp", name: "Total Protein", unit: "g/dL", refLow: 6.0, refHigh: 8.3, decimalPlaces: 1 },
      { id: "p-alb", name: "Albumin", unit: "g/dL", refLow: 3.5, refHigh: 5.2, criticalLow: 1.8, decimalPlaces: 1 },
    ],
  },
  {
    id: "test-kft",
    code: "BIO-003",
    name: "Renal Function Test (KFT / RFT) & Electrolytes",
    department: "Biochemistry",
    tubeType: "Gold / Red (SST / Serum)",
    specimen: "Serum (3 mL)",
    fastingRequired: false,
    tatMinutes: 75,
    price: 650,
    clinicalSignificance: "Assesses glomerular filtration, nitrogenous waste excretion, and electrolyte balance.",
    parameters: [
      { id: "p-urea", name: "Blood Urea", unit: "mg/dL", refLow: 15.0, refHigh: 40.0, criticalHigh: 120.0, decimalPlaces: 1 },
      { id: "p-creat", name: "Serum Creatinine", unit: "mg/dL", refLow: 0.7, refHigh: 1.3, criticalHigh: 5.0, decimalPlaces: 2 },
      { id: "p-uric", name: "Uric Acid", unit: "mg/dL", refLow: 3.5, refHigh: 7.2, decimalPlaces: 2 },
      { id: "p-na", name: "Sodium (Na+)", unit: "mEq/L", refLow: 136.0, refHigh: 145.0, criticalLow: 120.0, criticalHigh: 160.0, decimalPlaces: 1 },
      { id: "p-k", name: "Potassium (K+)", unit: "mEq/L", refLow: 3.5, refHigh: 5.1, criticalLow: 2.8, criticalHigh: 6.5, decimalPlaces: 2 },
      { id: "p-cl", name: "Chloride (Cl-)", unit: "mEq/L", refLow: 98.0, refHigh: 107.0, criticalLow: 80.0, criticalHigh: 125.0, decimalPlaces: 1 },
    ],
  },
  {
    id: "test-lipid",
    code: "BIO-004",
    name: "Lipid Profile Standard Cardiovascular Screen",
    department: "Biochemistry",
    tubeType: "Gold / Red (SST / Serum)",
    specimen: "Serum (3 mL)",
    fastingRequired: true,
    fastingHours: 12,
    tatMinutes: 90,
    price: 600,
    clinicalSignificance: "Evaluates dyslipidemia, atherosclerotic risk, and metabolic syndrome.",
    parameters: [
      { id: "p-tchol", name: "Total Cholesterol", unit: "mg/dL", refLow: 125.0, refHigh: 200.0, criticalHigh: 350.0, decimalPlaces: 0 },
      { id: "p-tg", name: "Triglycerides", unit: "mg/dL", refLow: 50.0, refHigh: 150.0, criticalHigh: 500.0, decimalPlaces: 0 },
      { id: "p-hdl", name: "HDL Good Cholesterol", unit: "mg/dL", refLow: 40.0, refHigh: 60.0, decimalPlaces: 0 },
      { id: "p-ldl", name: "LDL Bad Cholesterol", unit: "mg/dL", refLow: 50.0, refHigh: 100.0, criticalHigh: 220.0, decimalPlaces: 0 },
      { id: "p-vldl", name: "VLDL Cholesterol", unit: "mg/dL", refLow: 10.0, refHigh: 30.0, decimalPlaces: 0 },
    ],
  },
  {
    id: "test-hba1c",
    code: "BIO-005",
    name: "Glycated Hemoglobin (HbA1c) by HPLC Method",
    department: "Biochemistry",
    tubeType: "Lavender (EDTA)",
    specimen: "Whole Blood EDTA (2 mL)",
    fastingRequired: false,
    tatMinutes: 60,
    price: 450,
    clinicalSignificance: "Gold standard test for monitoring 3-month glycemic control in diabetes.",
    parameters: [
      { id: "p-hba1c", name: "HbA1c", unit: "%", refLow: 4.0, refHigh: 5.6, criticalHigh: 14.0, decimalPlaces: 1 },
      { id: "p-eag", name: "Estimated Average Glucose (eAG)", unit: "mg/dL", refLow: 70.0, refHigh: 115.0, decimalPlaces: 0 },
    ],
  },
  {
    id: "test-thyroid",
    code: "IMM-006",
    name: "Thyroid Profile Total (T3, T4, TSH Ultra)",
    department: "Immunology",
    tubeType: "Gold / Red (SST / Serum)",
    specimen: "Serum (3 mL)",
    fastingRequired: true,
    fastingHours: 8,
    tatMinutes: 120,
    price: 550,
    clinicalSignificance: "Evaluates hypothyroidism, hyperthyroidism, and anterior pituitary-thyroid axis.",
    parameters: [
      { id: "p-t3", name: "Total Triiodothyronine (T3)", unit: "ng/dL", refLow: 80.0, refHigh: 200.0, decimalPlaces: 1 },
      { id: "p-t4", name: "Total Thyroxine (T4)", unit: "µg/dL", refLow: 4.5, refHigh: 12.0, decimalPlaces: 1 },
      { id: "p-tsh", name: "TSH (3rd Gen Ultra)", unit: "µIU/mL", refLow: 0.35, refHigh: 4.94, criticalLow: 0.05, criticalHigh: 25.0, decimalPlaces: 2 },
    ],
  },
  {
    id: "test-cardiac-trop",
    code: "IMM-007",
    name: "Cardiac Troponin-I High Sensitivity (STAT)",
    department: "Immunology",
    tubeType: "Green (Sodium Heparin)",
    specimen: "Heparinized Plasma / Serum (2 mL)",
    fastingRequired: false,
    tatMinutes: 30,
    price: 1200,
    clinicalSignificance: "Critical cardiac biomarker for acute myocardial infarction (heart attack) triage.",
    parameters: [
      { id: "p-trop-i", name: "High Sensitivity Troponin-I", unit: "ng/L", refLow: 0.0, refHigh: 14.0, criticalHigh: 50.0, decimalPlaces: 1 },
    ],
  },
  {
    id: "test-urine-re",
    code: "MIC-008",
    name: "Complete Urine Routine & Microscopic Examination",
    department: "Microbiology",
    tubeType: "Sterile Container (Urine/Fluid)",
    specimen: "Clean Catch Midstream Urine (20 mL)",
    fastingRequired: false,
    tatMinutes: 45,
    price: 200,
    clinicalSignificance: "Evaluates urinary tract infection, proteinuria, hematuria, and renal calculi.",
    parameters: [
      { id: "p-u-ph", name: "Urine pH", unit: "", refLow: 5.0, refHigh: 7.5, decimalPlaces: 1 },
      { id: "p-u-sg", name: "Specific Gravity", unit: "", refLow: 1.005, refHigh: 1.030, decimalPlaces: 3 },
      { id: "p-u-sugar", name: "Urine Glucose", unit: "", textReference: "Nil", decimalPlaces: 0 },
      { id: "p-u-protein", name: "Urine Protein", unit: "", textReference: "Nil / Trace", decimalPlaces: 0 },
      { id: "p-u-pus", name: "Pus Cells (WBC)", unit: "/hpf", refLow: 0.0, refHigh: 5.0, criticalHigh: 50.0, decimalPlaces: 0 },
      { id: "p-u-rbc", name: "RBCs", unit: "/hpf", refLow: 0.0, refHigh: 2.0, criticalHigh: 30.0, decimalPlaces: 0 },
    ],
  },
];
